name: Create Release ZIP

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Configure Git
      run: |
        git config --global user.email "fgilde@gmail.com"
        git config --global user.name "Florian Gilde"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' 

    - name: Run build script
      run: powershell -ExecutionPolicy Bypass -File ./build.ps1 -version ${{ github.event.release.tag_name }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Aimmy2/bin/Release/TotallyNotAimmyV2_${{ github.event.release.tag_name }}.zip
        asset_name: ${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
