name: Create Release ZIP

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Configure Git
      run: |
        git config --global user.email "fgilde@gmail.com"
        git config --global user.name "fgilde"

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Stellt sicher, dass alle Branches und Tags vorhanden sind

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Run build script
      run: powershell -ExecutionPolicy Bypass -File ./build.ps1 -version ${{ github.event.release.tag_name }}

    - name: Upload release ZIP asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Aimmy2/bin/Release/Release_${{ github.event.release.tag_name }}.zip
        asset_name: ${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Installer.exe asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Aimmy2/bin/Release/Installer.exe
        asset_name: Installer.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
